#include <gbdk/platform.h>
#include <gb/gb.h>
#include <stdint.h>

#include "save.h"
#include "music.h"

// Replace with real tile/sprite data generated by `make assets`
// (see res/gfx/ and the png2asset rule in the Makefile).
static const uint8_t player_tile[16] = {
    0x3C, 0x3C, 0x42, 0x42, 0x81, 0x81, 0x99, 0x99,
    0x99, 0x99, 0x81, 0x81, 0x42, 0x42, 0x3C, 0x3C,
};

static save_data_t save;
static uint8_t px = 80, py = 72;

void main(void) {
    // Load prior progress if a valid battery save exists; otherwise
    // start fresh rather than trusting zeroed/garbage SRAM.
    if (save_load(&save)) {
        px = save.player_x;
        py = save.player_y;
    }

    set_sprite_data(0, 1, player_tile);
    set_sprite_tile(0, 0);
    move_sprite(0, px, py);

    SHOW_SPRITES;
    DISPLAY_ON;

    music_init();

    while (1) {
        uint8_t keys = joypad();

        if (keys & J_LEFT)  px--;
        if (keys & J_RIGHT) px++;
        if (keys & J_UP)    py--;
        if (keys & J_DOWN)  py++;

        if (keys & J_START) {
            save.player_x = px;
            save.player_y = py;
            save_write(&save);
        }

        move_sprite(0, px, py);
        music_update();
        vsync();
    }
}
